language: node_js

os: linux

dist: trusty

node_js:
  - '12'

branches:
  only:
    - master
    - production
    - demo

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm i -g npm@latest

install:
  - travis_retry npm --version

stages:
  - name: 'dev'
    if: branch = master
  - name: 'demo'
    if: branch = demo
  - name: 'prod'
    if: branch = production

jobs:
  include:
    - stage: 'dev'
      name: 'Deploy to Dev'
      script: skip
      deploy: &heroku
        provider: heroku
        app:
          master: nortan-dev
        api_key: $HEROKU_AUTH_TOKEN
        run: 'rm -rf src/app src/assets'
        strategy: git
    - stage: 'demo'
      name: 'Deploy to Staging'
      script: skip
      deploy: &heroku
        provider: heroku
        app:
          demo: nortan-demo
        api_key: $HEROKU_AUTH_TOKEN
        run: 'rm -rf src/app src/assets'
        strategy: git
    - stage: 'prod'
      name: 'Deploy to Production'
      script: skip
      deploy: &heroku
        provider: heroku
        app:
          production: nortan
        api_key: $HEROKU_AUTH_TOKEN
        run: 'rm -rf src/app src/assets'
        strategy: git
