language: node_js

sudo: false
dist: trusty

node_js:
  - '12'

branches:
  only:
    - master
    - production
    - demo

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm i -g npm@latest

install:
  - travis_retry npm i

git:
  depth: 1

jobs:
  include:
    - stage: 'Deploy to Dev'
      if: branch = master
      script: skip
      deploy: &heroku
        provider: heroku
        skip_cleanup: true
        app:
          master: nortan-dev
        api_key: $HEROKU_AUTH_TOKEN
        run: 'rm -rf src/app src/assets'
        strategy: git
      script: 'curl http://nortan-dev.herokuapp.com'
    - stage: 'Deploy to Staging'
      if: branch = production OR branch = demo
      script: skip
      deploy: &heroku
        provider: heroku
        skip_cleanup: true
        app:
          production: nortan-demo
          demo: nortan-demo
        api_key: $HEROKU_AUTH_TOKEN
        run: 'rm -rf src/app src/assets'
        strategy: git
    - stage: 'Deploy to Production'
      if: branch = production
      script: skip
      deploy:
        <<: *heroku
        on: production
        app:
          production: nortan
