language: node_js

sudo: false
dist: trusty

node_js:
  - '12'

branches:
  only:
    - master
    - production
    - demo

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm i -g npm@latest

install:
  - travis_retry npm i

git:
  depth: 1

jobs:
  include:
    - stage: 'Lint and Build Test'
      script: 'npm run lint:style'
      name: 'Lint'
    - script: 'npm run build'
      name: 'Build'
    - stage: 'Deploy to Dev'
      if: branch = master
      script: skip
      deploy: &heroku
        provider: heroku
        app:
          master: nortan-dev
        api_key: $HEROKU_AUTH_TOKEN
    - stage: 'Test Dev'
      if: branch = master
      script: 'curl http://nortan-dev.herokuapp.com'
    - stage: 'Deploy to Staging'
      if: branch = production
      script: skip
      deploy: &heroku
        provider: heroku
        app:
          production: nortan-demo
        api_key: $HEROKU_AUTH_TOKEN
    - stage: 'Test Staging'
      if: branch = production
      script: 'curl http://nortan-demo.herokuapp.com'
    - stage: 'Deploy to Production'
      if: branch = production
      script: skip
      deploy:
        <<: *heroku
        on: production
        app:
          production: nortan
    - stage: 'Test Production'
      if: branch = production
      script: 'curl http://nortan.herokuapp.com'
