language: node_js

sudo: false
dist: trusty

node_js:
  - '12'

branches:
  only:
    - master
    - production

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm i -g npm@latest

install:
  - travis_retry npm i

before_script:

script:
  - npm run lint:styles
  - npm run build:prod

deploy:
  provider: heroku
  api_key:
    secure: CxQcs/Kf69CCo/cOyWNRyqFGoF/5TCgU80s7GlWkZQEuq6dLe6Ed4r8SKhBzvCnCWVwfBGc38pXBDUgrTTBoKA1ssRgFSUbGzBDZBjNgy6UfFlrXibsWTbawbNQBgubR9ZFb2r+nXEM6uOLFd3o1fkF7n3cM8vXjvk8w/Eo4GrYt4ug83z13MBQ7DzkbR2Q8K+Titv5bgGPfNZRhw1FA2C6e+kFtp0KDIAoS+tYEqqZOAQZYUT0KhZaljDuwvAASOx32irpzoAyxPmDZoQPVHJHbPBFeAJoV2SUGkDRVQcIeDHYiL6KBRhXJPu7Z9Mqi88G1GQCo5ZV4x/ngwJ4xwgEdWk5A5PoeQbcFjBxt6gamU0jeiL5zNEYhnVjYLZk/oFQnWmN0WADkR+6KyOdySVoC/3xlTayBFuRAgMsl1bBQb4hH/L2PU7DLOOhguTalZcHehmSyLt2soCG6kbXslFf7HD6cAoc1hRtub5xKnl7LKSA9xUQasb1CditcpNL1okOxgsLDFqky7kJn1b1T0tnKdAQ6AcF2ljsVb8fYAoJnmnUd3u6MuSFEsjQowhX12a89XDKZgqt+KWrwjCmuM725kcYqpr86QhPJJ4IwMlCkapemhgaUFqFBzTekAT/Ei+tnlaG3xhQI8lKF7nP/cOOdjwRnTsOCaheU9cDRp60=
  app:
    master: nortan-dev
    production: nortan

git:
  depth: 1
